// Comprehensive Master Directory Dataset for Hidalgo County Democrats
// Auto-generated & Standardized for Federal, State, and County levels

export const CANDIDATE_DIRECTORY = [
  {
    id: "fed-talarico-james",
    name: "James Talarico",
    office: "U.S. Senator",
    level: "Federal",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "",
    email: "info@jamestalarico.com",
    website: "https://jamestalarico.com",
    donate_url: "https://secure.actblue.com/donate/talarico",
    twitter: "https://twitter.com/jamestalarico",
    facebook: "https://www.facebook.com/jamestalaricotx",
    instagram: "https://www.instagram.com/jamestalarico",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "fed-pulido-bobby",
    name: "Bobby Pulido",
    office: "U.S. Representative, TX CD 15",
    level: "Federal",
    type: "2026 Nominee",
    party: "Democrat",
    phone: "",
    email: "contact@bobbypulidofortexas.com",
    website: "https://bobbypulidofortexas.com",
    donate_url: "https://secure.actblue.com/donate/bobby-pulido",
    twitter: "",
    facebook: "https://www.facebook.com/bobbypulido",
    instagram: "https://www.instagram.com/bobbypulido4real",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "fed-cuellar-henry",
    name: "Henry Cuéllar",
    office: "U.S. Representative, TX CD 28",
    level: "Federal",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "202-225-1640",
    email: "",
    website: "https://cuellar.house.gov",
    donate_url: "https://secure.actblue.com/donate/henrycuellar",
    twitter: "https://twitter.com/RepCuellar",
    facebook: "https://www.facebook.com/RepHenryCuellar",
    instagram: "https://www.instagram.com/rephenrycuellar",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-hinojosa-gina",
    name: "Gina Hinojosa",
    office: "Governor of Texas",
    level: "State",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "",
    email: "info@ginahinojosa.com",
    website: "https://ginahinojosa.com",
    donate_url: "https://secure.actblue.com/donate/gina-hinojosa",
    twitter: "https://twitter.com/GinaForAustin",
    facebook: "https://www.facebook.com/ginahinojosatx",
    instagram: "https://www.instagram.com/ginahinojosa",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-goodwin-vicki",
    name: "Vicki Goodwin",
    office: "Lieutenant Governor",
    level: "State",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "",
    email: "vicki@vickigoodwin.com",
    website: "https://vickigoodwin.com",
    donate_url: "https://secure.actblue.com/donate/vicki-goodwin",
    twitter: "https://twitter.com/VickiForTexas",
    facebook: "https://www.facebook.com/VickiGoodwinTX",
    instagram: "https://www.instagram.com/vickigoodwintx",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-jaworski-joe",
    name: "Joe Jaworski",
    office: "Texas Attorney General",
    level: "State",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "",
    email: "joe@jaworskifortexas.com",
    website: "https://jaworskifortexas.com",
    donate_url: "https://secure.actblue.com/donate/jaworski-for-texas",
    twitter: "https://twitter.com/JoeJaworskiTX",
    facebook: "https://www.facebook.com/JaworskiForTexas",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-johnson-nathan",
    name: "Nathan Johnson",
    office: "Texas Attorney General",
    level: "State",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "",
    email: "info@nathanjohnsonfortexas.com",
    website: "https://nathanjohnsonfortexas.com",
    donate_url: "https://secure.actblue.com/donate/nathan-johnson",
    twitter: "https://twitter.com/NathanForTexas",
    facebook: "https://www.facebook.com/NathanForTexas",
    instagram: "https://www.instagram.com/nathanfortexas",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-tucker-clayton",
    name: "Clayton Tucker",
    office: "Agriculture Commissioner",
    level: "State",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "",
    email: "clayton@tuckerfortexas.com",
    website: "https://tuckerfortexas.com",
    donate_url: "https://secure.actblue.com/donate/clayton-tucker",
    twitter: "https://twitter.com/TuckerForTexas",
    facebook: "https://www.facebook.com/TuckerForTexas",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-garcia-thomas",
    name: "Thomas García",
    office: "State Board of Education, District 2",
    level: "State",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "",
    email: "info@thomasgarciafortexas.com",
    website: "",
    donate_url: "https://secure.actblue.com/donate/thomas-garcia-sboe",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-longoria-oscar",
    name: "Oscar Longoria",
    office: "State Representative, District 35",
    level: "State",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-584-8999",
    email: "oscar.longoria@house.texas.gov",
    website: "https://house.texas.gov/members/member-page/?district=35",
    donate_url: "https://secure.actblue.com/donate/oscar-longoria",
    twitter: "https://twitter.com/RepLongoria",
    facebook: "https://www.facebook.com/RepOscarLongoria",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-munoz-sergio",
    name: "Sergio Muñoz, Jr.",
    office: "State Representative, District 36",
    level: "State",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-381-5555",
    email: "sergio@sergiomunozjr.com",
    website: "https://house.texas.gov/members/member-page/?district=36",
    donate_url: "https://secure.actblue.com/donate/sergio-munoz-jr",
    twitter: "https://twitter.com/SergioMunozJr",
    facebook: "https://www.facebook.com/SergioMunozJr",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-martinez-armando",
    name: "Armando \"Mando\" Martínez",
    office: "State Representative, District 39",
    level: "State",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-493-7600",
    email: "andoconmando@yahoo.com",
    website: "https://house.texas.gov/members/member-page/?district=39",
    donate_url: "https://secure.actblue.com/donate/armando-martinez",
    twitter: "https://twitter.com/RepMando",
    facebook: "https://www.facebook.com/RepMandoMartinez",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-canales-terry",
    name: "Terry Canales",
    office: "State Representative, District 40",
    level: "State",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-578-9568",
    email: "Tcanales@rgvattorney.com",
    website: "https://house.texas.gov/members/member-page/?district=40",
    donate_url: "https://secure.actblue.com/donate/terry-canales",
    twitter: "https://twitter.com/TerryCanales40",
    facebook: "https://www.facebook.com/TerryCanalesTX",
    instagram: "https://www.instagram.com/terrycanales",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-holguin-eric",
    name: "Eric Holguín",
    office: "State Representative, District 41",
    level: "State",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-489-2889",
    email: "Eric@ericfortexas.com",
    website: "https://ericfortexas.com",
    donate_url: "https://secure.actblue.com/donate/eric-holguin-for-texas",
    twitter: "https://twitter.com/EricForTexas",
    facebook: "https://www.facebook.com/EricForTexas",
    instagram: "https://www.instagram.com/ericfortexas",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-haddad-seby",
    name: "Seby Haddad",
    office: "State Representative, District 41",
    level: "State",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-605-7762",
    email: "sebyhaddad@gmail.com",
    website: "",
    donate_url: "https://secure.actblue.com/donate/seby-haddad",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "state-salinas-julio",
    name: "Julio Salinas",
    office: "State Representative, District 41",
    level: "State",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "",
    email: "juliosalinasfortexas@gmail.com",
    website: "",
    donate_url: "https://secure.actblue.com/donate/julio-salinas",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "county-cortez-richard",
    name: "Ricardo \"Richard\" F. Cortez",
    office: "Hidalgo County Judge",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-648-5941",
    email: "rfcortezcpa@gmail.com",
    website: "https://www.hidalgocounty.us/101/County-Judge",
    donate_url: "https://secure.actblue.com/donate/richard-cortez",
    twitter: "",
    facebook: "https://www.facebook.com/JudgeRichardFCortez",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "county-palacios-terry",
    name: "Toribio \"Terry\" Palacios",
    office: "Criminal District Attorney",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-330-0788",
    email: "toribiopalacios@att.net",
    website: "https://www.hidalgocounty.us/108/Criminal-District-Attorney",
    donate_url: "",
    twitter: "",
    facebook: "https://www.facebook.com/DATerryPalacios",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "county-hinojosa-laura",
    name: "Laura Hinojosa",
    office: "District Clerk",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-605-1010",
    email: "lauraleehinojosa@gmail.com",
    website: "https://www.hidalgocounty.us/104/District-Clerk",
    donate_url: "",
    twitter: "",
    facebook: "https://www.facebook.com/LauraHinojosaDistrictClerk",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "county-guajardo-arturo",
    name: "Arturo Guajardo, Jr.",
    office: "County Clerk",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-279-6037",
    email: "arturo.guajardo@co.hidalgo.tx.us",
    website: "https://www.hidalgocounty.us/103/County-Clerk",
    donate_url: "",
    twitter: "",
    facebook: "https://www.facebook.com/ArturoGuajardoJrCountyClerk",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "county-leo-lita",
    name: "Lita L. Leo",
    office: "County Treasurer",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-279-8451",
    email: "lrain21@gmail.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "county-cantu-alejandro",
    name: "Alejandro Cantú",
    office: "County Treasurer",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-867-3650",
    email: "alemx16@hotmail.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "county-cantu-eddie",
    name: "Eddie Cantú, Jr.",
    office: "County Commissioner, Precinct 2",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-454-7247",
    email: "eddiecantu@me.com",
    website: "https://www.hidalgocounty.us/112/Precinct-2",
    donate_url: "",
    twitter: "",
    facebook: "https://www.facebook.com/CommissionerEddieCantu",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "county-torres-ellie",
    name: "Ellie Torres",
    office: "County Commissioner, Precinct 4",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-279-4874",
    email: "jdredbail@yahoo.com",
    website: "https://www.hidalgocounty.us/114/Precinct-4",
    donate_url: "",
    twitter: "",
    facebook: "https://www.facebook.com/EllieTorresPct4",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "county-marichalar-daniel",
    name: "Daniel Marichalar",
    office: "Constable, Precinct 5",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-756-0438",
    email: "Danman182142@icloud.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "county-arce-jorgeluis",
    name: "Jorge Luis Arce",
    office: "Constable, Precinct 5",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-379-0792",
    email: "jorge.arce62@gmail.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-zamora-juan",
    name: "Juan J. Zamora",
    office: "206th State District Court",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-420-4878",
    email: "prisylla@etiksolutions.us",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-regalado-lucia",
    name: "Lucia Regalado",
    office: "206th State District Court",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "",
    email: "luciaregaladoforjudge@gmail.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-cuellar-marla",
    name: "Marla Cuéllar",
    office: "275th State District Court",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-207-7690",
    email: "marla3esq@yahoo.com",
    website: "https://www.hidalgocounty.us/146/275th-District-Court",
    donate_url: "",
    twitter: "",
    facebook: "https://www.facebook.com/JudgeMarlaCuellar",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-gonzalez-noe",
    name: "Noe González",
    office: "370th State District Court",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-457-9643",
    email: "GNZ3@hotmail.com",
    website: "https://www.hidalgocounty.us/150/370th-District-Court",
    donate_url: "",
    twitter: "",
    facebook: "https://www.facebook.com/JudgeNoeGonzalez",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-gonzalez-rudy",
    name: "Rodolfo \"Rudy\" González",
    office: "County Court at Law No. 1",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-358-6199",
    email: "rudy.gonzale@co.hidalgo.tx.us",
    website: "https://www.hidalgocounty.us/152/County-Court-at-Law-1",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-palacios-jaime",
    name: "Jaime \"Jay\" Palacios",
    office: "County Court at Law No. 2",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-318-2380",
    email: "Jaime.Palacios44@gmail.com",
    website: "https://www.hidalgocounty.us/153/County-Court-at-Law-2",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-garza-fred",
    name: "Federico \"Fred\" Garza, Jr.",
    office: "County Court at Law No. 4",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-330-1649",
    email: "fredgar0324@gmail.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-garcia-perez-katherine",
    name: "Katherine García Pérez",
    office: "County Court at Law No. 4",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-381-1800",
    email: "katherine@kperezlaw.net",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-cantu-arnoldo",
    name: "Arnoldo Cantú, Jr.",
    office: "County Court at Law No. 5",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-498-7885",
    email: "arnoldocantujr@gmail.com",
    website: "https://www.hidalgocounty.us/156/County-Court-at-Law-5",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-garcia-albert",
    name: "Albert García",
    office: "County Court at Law No. 6",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-460-7180",
    email: "albertgarcia1113@yahoo.com",
    website: "https://www.hidalgocounty.us/157/County-Court-at-Law-6",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-maldonado-omar",
    name: "Enrique Omar Maldonado",
    office: "County Court at Law No. 8",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-212-6040",
    email: "Eomarmaldonado@gmail.com",
    website: "https://www.hidalgocounty.us/159/County-Court-at-Law-8",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-garcia-joanne",
    name: "JoAnne García",
    office: "Probate Court No. 1",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-624-8402",
    email: "joannefojudge@gmail.com",
    website: "https://www.hidalgocounty.us/161/Probate-Court-1",
    donate_url: "",
    twitter: "",
    facebook: "https://www.facebook.com/JudgeJoAnneGarcia",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jud-garza-aissa",
    name: "Aissa Garza",
    office: "Probate Court No. 2",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "210-552-9773",
    email: "aissa@aissalaw.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jp-gonzalez-andrew",
    name: "Daniel Andrew González",
    office: "Justice of the Peace, Precinct 1, Pl. 2",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-975-7651",
    email: "drewgonzalez10@gmail.com",
    website: "https://www.hidalgocounty.us/171/JP-Pct-1-Pl-2",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jp-gutierrez-cynthia",
    name: "Cynthia Gutiérrez",
    office: "Justice of the Peace, Precinct 2, Pl. 1",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-515-3502",
    email: "drcynthia35@aol.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jp-zambrano-jorgeluis",
    name: "Jorge Luis Zambrano",
    office: "Justice of the Peace, Precinct 2, Pl. 1",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-800-3623",
    email: "jorgezambranocampaign2026@gmail.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jp-sanchez-lisamarie",
    name: "Lisa Marie Sánchez",
    office: "Justice of the Peace, Precinct 2, Pl. 1",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-534-5990",
    email: "lisamariesanchez1973@gmail.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jp-munoz-jaime",
    name: "Jaime Jerry Muñoz",
    office: "Justice of the Peace, Precinct 2, Pl. 2",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-683-5596",
    email: "jaimejmunoz@aol.com",
    website: "https://www.hidalgocounty.us/173/JP-Pct-2-Pl-2",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jp-pena-juanjose",
    name: "Juan José Peña",
    office: "Justice of the Peace, Precinct 3, Pl. 2",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-227-3215",
    email: "pena.juan1@gmail.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jp-trevino-sonia",
    name: "Sonia Melissa Treviño",
    office: "Justice of the Peace, Precinct 3, Pl. 2",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-519-3111",
    email: "soniatrevino3232@gmail.com",
    website: "https://www.hidalgocounty.us/175/JP-Pct-3-Pl-2",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jp-maldonado-andre",
    name: "Arnold André Maldonado",
    office: "Justice of the Peace, Precinct 4, Pl. 2",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-607-9484",
    email: "Andre@maldonadolawpllc.com",
    website: "https://www.hidalgocounty.us/177/JP-Pct-4-Pl-2",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jp-pena-jason",
    name: "Jason Peña",
    office: "Justice of the Peace, Precinct 5, Pl. 1",
    level: "County",
    type: "Elected Incumbent",
    party: "Democrat",
    phone: "956-375-8851",
    email: "judgejasonpena@gmail.com",
    website: "https://www.hidalgocounty.us/178/JP-Pct-5-Pl-1",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  },
  {
    id: "jp-hernandez-victor",
    name: "Victor Luis Hernández",
    office: "Justice of the Peace, Precinct 5, Pl. 1",
    level: "County",
    type: "2026 Candidate",
    party: "Democrat",
    phone: "956-472-3927",
    email: "vich34@aol.com",
    website: "",
    donate_url: "",
    twitter: "",
    facebook: "",
    instagram: "",
    photo_url: "images/facebook_1656248751972_6946810765393131439.webp"
  }
];
